### ISSUE TITLE
提两个建议

### ISSUE THREAD

**Issue by imoldchen** [Jasper-1024/MyPrivacy#1]
1 .新版本更新日志说加入了xprivacy，然后几乎之前禁止读取已安装应用的app都运行崩溃了，是否可以把禁用的一些服务或者权限列出来，让用户自己开启关闭，而不是单一项（弄个高级模式选项什么的）
2 . 测试对象可以考虑目标app为阿里钉钉，它几乎代表了目前国内厂商最底线获取隐私手段之最。

**Comment by Jasper-1024** [comment]
@imoldchen 正在考虑这个选择 既加入一个实验选择  对应每个权限下开放用户自行配置.
阿里钉钉,说实话 就是获取定位的方式恶心,其实阿里系的定位都一个样子,能用的数据都用上了,,,,我并没有专门测试手机,都是在自用的上面进行,阿里钉钉,,,等收一个二手的时候会考虑安装,,,

**Comment by Jasper-1024** [comment]
@imoldchen 已在2.01版本中完成
