### ISSUE TITLE
应用闪退

### ISSUE THREAD

**Issue by w1324296** [Jasper-1024/MyPrivacy#2]
使用这个模块后，华夏万家等APP会闪退，个人猜想是在获取APP列表时出错了，是不是禁止他们获取列表数据时用的方法太僵硬了些？如果返回的是空数据或伪造的数据而不是禁止函数调用呢？求点拨

**Comment by Jasper-1024** [comment]
现在实际返回的就是空数据.闪退的你试试看具体是那个API被禁止之后导致的.
开放到最底层API就是为了防止禁用了一组闪退,不知道那个.

**Comment by w1324296** [comment]
我也不清楚哎，没找到日志
