### ISSUE TITLE
LocationManager 类名写错导致插件全部失效

### ISSUE THREAD

**Issue by tiann** [Jasper-1024/MyPrivacy#3]
https://github.com/Jasper-1024/MyPrivacy/blob/master/app/src/main/java/com/jasperhale/myprivacy/XposedHook/Hook/LocationManager.java#L61

这个类叫 LocationManager，实际上需要hook的类为 `android.location.LocationManager`

这里有详细分析：

https://github.com/taichi-framework/TaiChi/issues/133#issuecomment-466863818

**Comment by Jasper-1024** [comment]
非常抱歉，这个模块已停止更新，个人水平有限，架构根本上就错了，继续维护的成本偏高且 开发背景是xprivacy 不太兼容xposed N及以上，但原作者的xprivacylua已经完成度非常高，继续维护意义不大，遂下架了应用。

**Comment by Jasper-1024** [comment]
个人目前主业非Android方向，之后我会在主页 写入停止更新。
目前手头没有Android的设备，会看一下相关代码，尝试修正一下，但还是推荐使用xprivacy lua

**Comment by tiann** [comment]
谢谢答复！
